stages:
  - test-ut
  - build
  - test-ac
  - package
  - pre-deploy

zoo-testut-job:
  stage: test-ut
  script:
  - flake8 /builds/root/hello-world/hello.py
  - yapf -r -d  /builds/root/hello-world
  only:
  - pushes
  except:
  - master

zoo-build-job:
  stage: build
  script:
  - service docker start
  - docker build -t 192.168.185.78:5000/hello:$CI_COMMIT_REF_NAME ./
  - docker push 192.168.185.78:5000/hello:$CI_COMMIT_REF_NAME
  - echo "kubectl create deployment hello-world"
  only:
  - branches
  except:
  - master

zoo-testac-job:
  stage: test-ac
  script: echo "actest ok"
  only:
  - branches
  except:
  - master

zoo-package-job:
  stage: package
  script: echo "push image to repository"
  only:
  - master

zoo-pre-deploy-job:
  stage: pre-deploy
  script: echo "deploy to pre-deploy"
  only:
  - master
  when: manual

