stages:
  - test-ut
  - test-ac

test-ut:
  stage: test-ut
  script:
  - flake8 /builds/root/hello-world/hello.py
  - yapf -r -d /builds/root/hello-world/hello.py 

test-ac:
  stage: test-ac
  script: echo "ok" 
  only:
  - master
