stages:
  - test-ut
  - build
  - test-ac
  - package
  - pre-deploy

zoo-testut-job:
  stage: test-ut
  script:
  - flake8 /builds/root/hello-world/hello.py
  - yapf -r -d /builds/root/hello-world/hello.py
  only:
  - pushes

zoo-build-job:
  stage: build
  script:
  - cd /builds/root/hello-world/ && docker build -t hello:$CI_COMMIT_REF_NAME
  - docker run -d hello:$CI_COMMIT_REF_NAME
  only:
    - master

zoo-testac-job:
  stage: test-ac
  script: echo "actest ok"
  only:
  - master

zoo-package-job:
  stage: package
  script: echo "push image to repository"
  only:
  - master

zoo-pre-deploy-job:
  stage: pre-deploy
  script: echo "deploy to pre-deploy"
  only:
  - master

