stages:
  - test-ut
  - build
  - test-ac
  - package
  - pre-deploy

testut:
  stage: test-ut
  script:
  - flake8 /root/hello-world/
  - yapf -r -d  /root/hello-world
  only:
  - pushes
  except:
  - master
  variables:
    CI_DEBUG_TRACE: "true"

build-docker:
  stage: build
  script:
  - export CI_COMMIT=`cd $CI_PROJECT_DIR && git rev-parse --short HEAD`
  - docker build -t 192.168.185.78:5000/hello:$CI_COMMIT /root/hello-world
  - docker push 192.168.185.78:5000/hello:$CI_COMMIT_REF_NAME
  only:
  - branches
  except:
  - master

testac:
  stage: test-ac
  script: echo "actest ok"
  only:
  - branches
  except:
  - master

upload_package:
  stage: package
  script: echo "push image to repository"
  only:
  - master

pre-deploy:
  stage: pre-deploy
  script: echo "deploy to pre-deploy"
  only:
  - master
  when: manual

